### PR TITLE
added support for symbol lookup at multiple locations

### PR DESCRIPTION
**Pull request by sriks**
Added support to lookup at multiple symbol locations. This removes file not found errors by performing additional lookups in `PrivateFrameworks` etc., hence improves symbolication result by giving complete coverage. This results in subtle improvements in the end result

before:
`libobjc.A.dylib  2195ADFF         objc_exception_throw`

after:
`libobjc.A.dylib  2195ADFF         objc_exception_throw (in libobjc.A.dylib) + 39`

before
`GraphicsServices 2331BAF9         GSEventRunModal`

after
`GraphicsServices 2331BAF9         GSEventRunModal (in GraphicsServices) + 161`

### CODE REVIEW

**Comment by zackehh** [comment]
@sriks I tried this PR on the sample crash and still only see `GraphicsServices 2331BAF9 GSEventRunModal`. Should I not be seeing `GraphicsServices 2331BAF9 GSEventRunModal (in GraphicsServices) + 161`?

**Comment by vasil9v** [comment]
i tested this on preprod with `node symbolicate-cli.js --dsym sample/crash.dsym --crash sample/crash.json`
It does show the additional information for those 2 items:
```
> command: atosl -o /opt/xcode/latest/Symbols/usr/lib/libobjc.A.dylib --arch armv7s -l 21954000 2195ADFF
> stdout: objc_exception_throw (in libobjc.A.dylib) + 39
> , stderr: 
36a40,42
> command: atosl -o /opt/xcode/latest/Symbols/System/Library/PrivateFrameworks/GraphicsServices.framework/GraphicsServices --arch armv7s -l 23312000 2331BAF9
> stdout: GSEventRunModal (in GraphicsServices) + 161
> , stderr: 
68c74
< libobjc.A.dylib  2195ADFF         objc_exception_throw                                                                
---
> libobjc.A.dylib  2195ADFF         objc_exception_throw (in libobjc.A.dylib) + 39                                      
84c90
< GraphicsServices 2331BAF9         GSEventRunModal                                                                     
---
> GraphicsServices 2331BAF9         GSEventRunModal (in GraphicsServices) + 161  
```

But note there are still the same "no such file" errors in stderr for some items:
```
ubuntu@ip-10-231-44-9:~/appc-crash-analytics/node_modules/symbolication$ cat out1 | grep "such file"
stdout: , stderr: atosl: atosl.c:1193: unable to open `/opt/xcode/latest/Symbols/usr/lib/system/libobjc.A.dylib': No such file or directory
stdout: , stderr: atosl: atosl.c:1193: unable to open `/opt/xcode/latest/Symbols/System/Library/Frameworks/GraphicsServices.framework/GraphicsServices': No such file or directory
ubuntu@ip-10-231-44-9:~/appc-crash-analytics/node_modules/symbolication$ cat out2 | grep "such file"
stdout: , stderr: atosl: atosl.c:1193: unable to open `/opt/xcode/latest/Symbols/usr/lib/system/libobjc.A.dylib': No such file or directory
stdout: , stderr: atosl: atosl.c:1193: unable to open `/opt/xcode/latest/Symbols/System/Library/Frameworks/GraphicsServices.framework/GraphicsServices': No such file or directory
```

**Comment by sriks** [comment]
@vasil9v Those not found errors cannot be solved because we look at `Frameworks` path and if not found we look at `PrivateFrameworks` path. So the first lookup will result in the error.

**Comment by vasil9v** [comment]
@sriks ah i got ya, thanks

**Comment by zackehh** [comment]
This change has been incorporated into #2

**Pull request closed without merging**
